# build react
FROM node:latest as build

ARG MYFILESYSTEM_BACKEND_HOST

ENV MYFILESYSTEM_BACKEND_HOST ${MYFILESYSTEM_BACKEND_HOST}

WORKDIR /app

COPY . .

RUN npm install

RUN npm run build

# serve web paage by nginx
FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/my_filesystem

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
