image: node:latest

cache:
  paths:
    - my-filesystem-portal/node_modules/
    - backend/node_modules/

stages:
  - test
  - build
  - deploy
  - format
  - lint

test_frontend:
  stage: test
  script:
    - cd my-filesystem-portal
    - npm install
    - npm run testCI

coverage_frontend:
  stage: test
  script:
    - cd my-filesystem-portal
    - npm install
    - npm run coverage
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'

format_backend:
  stage: format
  script:
    - cd backend
    - npm install
    - npx prettier -c .

format_frontend:
  stage: format
  script:
    - cd my-filesystem-portal
    - npm install
    - npx prettier -c .

lint_frontend:
  stage: lint
  script:
    - cd my-filesystem-portal
    - npm install
    - npm run lint

test_api:
  stage: test
  script:
    - cd backend
    - npm install
    - npm run test-api

test_db:
  stage: test
  services:
    - name: mysql:latest
      alias: mysql
  variables:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_ROOT_HOST: "%"
    MYSQL_DATABASE: db
    DATABASE_URL: mysql://root:password@mysql:3306/db
    CI: "true"
  script:
    - cd backend
    - npm install
    - npx prisma generate
    - npx prisma migrate dev
    - npm run test-db

coverage_backend:
  stage: test
  services:
    - name: mysql:latest
      alias: mysql
  variables:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_ROOT_HOST: "%"
    MYSQL_DATABASE: db
    DATABASE_URL: mysql://root:password@mysql:3306/db
    CI: "true"
  script:
    - cd backend
    - npm install
    - npx prisma generate
    - npx prisma migrate dev
    - npm run coverage
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
