version: '3.8'

services:

  frontend:
    image: my_filesystem_portal
    build: ./my-filesystem-portal
    ports:
      - 80:80

  server:
    build:
      context: ./backend
    ports:
      - 3000:3000

  db:
    image: mysql/mysql-server:latest
    restart: always
    ports:
      - 53306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: password
    

