version: '3.8'

services:

  frontend:
    image: my_filesystem_portal
    build: ./my-filesystem-portal
    ports:
      - 80:80

  db:
    image: mysql/mysql-server:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 63306:63306
    environment:
      MYSQL_ROOT_PASSWORD: splung3
      MYSQL_DATABASE: splunge_db
      MYSQL_ROOT_HOST: "%"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: splung3
    ports: 
      - "60080:80"
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
