version: '3.8'

services:
  db:
    image: mysql/mysql-server:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: db

  frontend:
    image: my-filesystem-portal:latest
    build:
      context: ./my-filesystem-portal
      args:
        - MYFILESYSTEM_BACKEND_HOST=localhost
    ports:
      - 80:80

  server:
    hostname: server
    build:
      context: ./backend
      args:
        - JWT_SECRET=03cef2fd6d0b1ca7
        - BACKEND_DOMAIN=http://localhost:3000
        - DATABASE_URL=mysql://root:password@db:3306/db
    ports:
      - 3000:3000

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
